chore(#140) lint、deployオプションを廃止し、actionの値によって処理を分岐するよう修正

diff --git a/.github/actions/infra/deploy/cockroach/action.yml b/.github/actions/infra/deploy/cockroach/action.yml
--- a/.github/actions/infra/deploy/cockroach/action.yml
+++ b/.github/actions/infra/deploy/cockroach/action.yml
@@ -8,12 +8,9 @@ inputs:
   project_prefix:
     description: "service prefix."
     required: true
-  deploy:
-    description: "whether to deploy. true/false. default true."
-    default: 'true'
-  lint:
-    description: "whether to lint. true/false. default true."
-    default: 'true'
+  action:
+    description: "execution action : lint or preview or deploy"
+    required: true
   gcp_cloud_storage_terraform_bucket:
     description: "name of google cloud storage bucket for tfstate"
     required: true
@@ -30,7 +27,13 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Check action
+      if: ${{ inputs.action != 'lint' && inputs.action != 'preview' && inputs.action != 'deploy' }}
+      run: echo "invalid action ${{ inputs.action }}." && exit 1
+      shell: sh
+
     - name: Download .tfstate file from GCS
+      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate terraform.tfstate
       shell: sh
@@ -41,19 +44,19 @@ runs:
       shell: sh
     
     - name: Terraform format
-      if: ${{ inputs.lint == 'true' }}
+      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: terraform fmt -recursive -check
       shell: sh
 
     - name: Terraform validate
-      if: ${{ inputs.lint == 'true' }}
+      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: terraform validate
       shell: sh
 
     - name: Terraform plan
-      if: ${{ inputs.lint == 'true' }}
+      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       env: 
         COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
@@ -65,7 +68,7 @@ runs:
       shell: sh
 
     - name: Terraform apply
-      if: ${{ inputs.deploy == 'true' }}
+      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}  
       env: 
         COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
@@ -78,7 +81,7 @@ runs:
       shell: sh
 
     - name: Upload .tfstate file to GCS
-      if: ${{ inputs.deploy == 'true' }}
+      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate
       shell: sh
diff --git a/.github/actions/infra/deploy/gcp/action.yml b/.github/actions/infra/deploy/gcp/action.yml
--- a/.github/actions/infra/deploy/gcp/action.yml
+++ b/.github/actions/infra/deploy/gcp/action.yml
@@ -7,12 +7,9 @@ inputs:
     required: true
   project_prefix:
     description: "service prefix."
-  deploy:
-    description: "whether to deploy. true/false. default true."
-    default: 'true'
-  lint:
-    description: "whether to lint. true/false. default true."
-    default: 'true'
+  action:
+    description: "execution action : lint or preview or deploy"
+    required: true
   gcp_project_id:
     description: "gcp project id"
     required: true
@@ -35,7 +32,13 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Check action
+      if: ${{ inputs.action != 'lint' && inputs.action != 'preview' && inputs.action != 'deploy' }}
+      run: echo "invalid action ${{ inputs.action }}." && exit 1
+      shell: sh
+
     - name: Download .tfstate file from GCS
+      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/gcp/terraform.tfstate terraform.tfstate
       shell: sh
@@ -46,19 +49,19 @@ runs:
       shell: sh
     
     - name: Terraform format
-      if: ${{ inputs.lint == 'true' }}
+      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: terraform fmt -recursive -check
       shell: sh
     
     - name: Terraform validate
-      if: ${{ inputs.lint == 'true' }}
+      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: terraform validate
       shell: sh
 
     - name: Terraform plan
-      if: ${{ inputs.lint == 'true' }}
+      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: |
         terraform plan \
@@ -72,7 +75,7 @@ runs:
       shell: sh
 
     - name: Terraform apply
-      if: ${{ inputs.deploy == 'true' }}
+      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}          
       run: |
         terraform apply \
@@ -87,7 +90,7 @@ runs:
       shell: sh
 
     - name: Upload .tfstate file to GCS
-      if: ${{ inputs.deploy == 'true' }}
+      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
       working-directory: ${{ inputs.working-directory }}
       run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/gcp/terraform.tfstate
       shell: sh
